### ISSUE TITLE
python3 test regression (test2)

### ISSUE THREAD

**Issue by anthraxx** [google/enjarify#33]
Hi,
I'm a package maintainer and while building enjarify in a CI to early catch problems I have detected that the test2 is failing.
Python version: 3.5.2
commit: 2a94b403259e9e432fbd9607926db50286de6bc5
log:
```
==> Starting check()...
running test test1
running test test2
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/build/enjarify-git/src/enjarify-git/enjarify/runtests.py", line 46, in <module>
    executeTest('test{}'.format(i), opts)
  File "/build/enjarify-git/src/enjarify-git/enjarify/runtests.py", line 40, in executeTest
    assert result == expected
AssertionError
==> ERROR: A failure occurred in check().
    Aborting...
==> ERROR: Build failed
```

**Comment by Storyyeller** [comment]
Did the test pass with a previous version of Python? Note that this test invokes java, so changing the java installation could cause it to fail.

**Comment by anthraxx** [comment]
@Storyyeller hard to tell, but investigating a bit further the release version also fails with its tests. So it may indeed be either changes to python or changes in java. Do the tests still pass for you?

java: 8.u112
python: 3.5.2

**Comment by Storyyeller** [comment]
I generally run all the tests before pushing any changes. I don't remember the exact version of Python or Java I have though.

Anyway, if you're looking for regressions in Python rather than Enjarify itself, it would be better to use hashtests.py rather than runtests.py. Hashtests simply runs Enjarify on the test files and hashes the output, making it easy to detect differences between Python implementations, without worrying about Java flakiness. Unfortunately, it currently takes 20+ minutes because it runs with every possible combination of options. Perhaps something like hashtests, but running fewer iterations would be most useful for you?

**Comment by anthraxx** [comment]
The changes seem to be related to java, not related to python, however i get the same results when trying with java 7.u111. So it looks like some java assambly changed?

```
=====> RESULT:
testConsts
Hello, World!
0x0.0p0
null
0x0.0p0
ffff8000
NaN
NaN
c203126f
-0x1.0624dep5
-0x1.0624dep5
0
0x0.0p0
0x0.0p0
NaN
ffff8000
0x1.0p0
-0x1.0624dep5
c203126f
0x0.0p0
0x0.0p0
0
0x1.fcp6
testFields
0x0.0p0
0
Code
null
22b
1
0
NaN
40815c70a3d70a3d
0x0.0p0
testFillArray
[100, 101, 102, 103, 32767]
[-1073709056, -32768, -1073709056, -32768, -1073709056]
null

=====> EXPECTED:
testConsts
Hello, World!
0x0.0p0
null
0x0.0p0
ffff8000
NaN
NaN
c203126f
-0x1.0624dep5
-0x1.0624dep5
0
0x0.0p0
0x0.0p0
NaN
ffff8000
0x1.0p0
-0x1.0624dep5
c203126f
0x0.0p0
0x0.0p0
0
0x1.fcp6
testFields
0x0.0p0
0
Code
null
22b
1
20
NaN
40815c70a3d70a3d
0x0.0p0
testFillArray
[100, 101, 102, 103, 32767]
[-1073709056, -32768, -1073709056, -32768, -1073709056]
null

```

The difference between them:

```
# diff result.txt expected.txt 
31c31
< 0
---
> 20
38a39
> 

```

**Comment by anthraxx** [comment]
@Storyyeller Hm maybe, if you tell me thats more useful. 20 minutes is a really really long time :yum: The primary goal is to have tests that detect regression before i ship enjarify to the end-users.

**Comment by Storyyeller** [comment]
I just confirmed that the tests work on my machine. I'm using Python 3.4.3 and Java 
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

If your goal is to detect regressions in Enjarify itself and your running the unmodified source, then I don't think there is much point in running the tests, especially since I already run them myself.

But if you provide more information about your process and users, then I can take it into consideration if I make changes to Enjarify in the future. Unfortunately, the stuff most likely to break (OS specific issues) are also not feasible to test.

**Comment by anthraxx** [comment]
@Storyyeller well you should know software development is not that easy :yum: Regressions may occure because of upstream changes in dependencies like python or java. At the end it may make enjarify to not run. If the upstream changes are expected and not a but then a newer version indeed introduced a incompatibility in enjarify itself and i guess you expect enjarify to run on other setups then your own _jokingly_.
Exactly out of this reasons I'm pretty sure that i really want to run tests :smile_cat:

**Comment by Storyyeller** [comment]
A change to Java won't break Enjarify. At worst, it will break the code that is produced.

As mentioned before, the best way to detect regressions in Python is to use hashtests.py. To speed things up, I'd suggest changing 
    for bits in range(256):
        opts = options.Options(*[bool(bits & (1 << b)) for b in range(8)])

to
for opts in [options.NONE, options.PRETTY, options.ALL]:

**Comment by Storyyeller** [comment]
While you're here, I was wondering what you thought about dropping support for overwrite protection (i.e. removing the need for the -f flag). The only reason I put that in is because dex2jar did it and I wanted a similar interface to ease transition, but I found that in practice it is just annoying and useless.

**Comment by Storyyeller** [comment]
P.S. Have you tried out the Rust version? It's a lot faster (roughly 10x faster than Python).

**Comment by anthraxx** [comment]
@Storyyeller well i don't have strong opinions about the `-f` flag, its up to you. `cp` doesn't need a -f either :stuck_out_tongue_closed_eyes: People should be aware what they do so i would be fine dropping that.

**Comment by anthraxx** [comment]
@Storyyeller I don't know the rust version yet, can you point me to it?

PS Thanks for your fast responses, testing the hashtests way right now.

**Comment by Storyyeller** [comment]
You can find the Rust version on the go branch in enjarify-rs. https://github.com/google/enjarify/tree/go/enjarify-rs

I wrote it as an experiment, so it's not well documented, but it should work. 

There's also a go version on the same branch, but the rust version is faster.
